### ISSUE TITLE
Duplication de js et de css.

### ISSUE THREAD

**Issue by BlackPowerC** [SpecialTeam39/Open-Trade#2]
Je lance le sujet simplement.
Dans le repertoire *public*, qui contient des ressources (img, js, css, ...), il y a trois repertoires qui semble avoir un contenu presque identique.
Pour régler le problème je vais fusionner les trois dossiers !
Vous en pensez quoi ?

**Comment by thiernoalhassane** [comment]
cela peut causer des problémes vu que tu as préciser que c'est presque identique et non totalement identique
